#!/bin/bash
red=`tput setaf 1`
green=`tput setaf 2`
nc=`tput sgr0`

if [ -z `docker ps -q --no-trunc | grep $(docker-compose ps -q gogs)` ]; then
    if [ -e postgres-password.txt ]
    then
        POSTGRES_PASSWORD=`cat postgres-password.txt`
        printf "${green}[RUNNING]${nc} POSTGRES_PASSWORD=$POSTGRES_PASSWORD doccker-compose up -d"
        POSTGRES_PASSWORD=$POSTGRES_PASSWORD docker-compose up -d
    else
        echo "${red}[ERROR]${nc} The file 'postgres-password.txt' was not found:" 
        echo "you must create a one line file named 'postgres-password.txt'" 
        echo "with a password for the postgres admin user."
    fi
else
    echo "${red}[ERROR]${nc} 'dev-tools' are alreay running in the background run './stop' to stop them"
fi